config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :markets, only: [:index, :show]

  resources :vendors, only: [:show]
  # get '/markets/:market_id', to: 'markets#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController

  def index
    facade = MarketFacade.new
    @markets = facade.markets 
    
  end
  
  def show
    # require 'pry';binding.pry
    facade = MarketFacade.new
    @market = facade.market(params[:id])
    @vendors = facade.vendors(params[:id])
    # require 'pry';binding.pry
    # @vendor_name = VendorFacade.new.vendor(params)
  end


  private

  # def facade
  #   MarketShowFacade.new(params[:id])
  # end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<h1>Markets</h1>
<% @markets.each do |market| %>
  <ul class="market">
    <li class="name"><%= market.name %></li>
    <li class="city"><%= market.city %></li>
    <li class="state"><%= market.state %></li>
    <li><%= button_to "Info for this Market", market_path(market.market_id), method: :get %></li>
  </ul>
<% end %>

app/views/markets/show.html.erb
<h2><%= "#{@market.name}"%></h2>
<p> <%= @market.street %></p>
<p> <%= "#{@market.city}, #{@market.state} #{@market.zip}" %></p>



<h3>Vendors at our Market:</h3>
<% @vendors.each do |vendor| %>
  <ul class="vendor">
   <%= link_to "#{vendor.name}", vendor_path(vendor.vendor_id), method: :get %>
  </ul>
<% end %>